TRANSACTION_TYPE_DEBIT = "debit"
TRANSACTION_TYPE_CREDIT = "credit"
TRANSACTION_TYPES = ((TRANSACTION_TYPE_DEBIT, "Debit"), (TRANSACTION_TYPE_CREDIT, "Credit"))

WALLET_STATUS_ENABLED = "enabled"
WALLET_STATUS_DISABLED = "disabled"
WALLET_STATUSES = ((WALLET_STATUS_ENABLED, "Enabled"), (WALLET_STATUS_DISABLED, "Disabled"))
